[package]
authors = ["Wil Thomason <wbthomason@cs.cornell.edu>", "Xavier Cambar <xcambar@gmail.com>"]
name = "purs"
version = "0.2.0"

[dependencies]
ansi_term = "~0.11.0"
clap      = "~2.32.0"
git2      = "~0.8.0"
dirs      = "~2.0.0"
