[package]
authors = ["Wil Thomason <wbthomason@cs.cornell.edu>", "Xavier Cambar <xcambar@gmail.com>"]
name = "purs"
version = "0.2.0"

[dependencies]
ansi_term = "0.11.0"
clap = "2.32.0"
git2 = "0.7.2"
regex = "1.0.1"
tico = "1.0.0"
